ARG IMAGE_NAME="${IMAGE_NAME:-silverblue}"
ARG SOURCE_IMAGE="${SOURCE_IMAGE:-bluebase}"
ARG BASE_IMAGE="ghcr.io/ny5re/${SOURCE_IMAGE}"
ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION:-37}"

FROM ${BASE_IMAGE}:${FEDORA_MAJOR_VERSION} AS builder

ARG IMAGE_NAME="${IMAGE_NAME}"
ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION}"

# The default image registry to write to policy.json and cosign.yaml
ARG IMAGE_REGISTRY=ghcr.io/ny5re

COPY etc/dconf/db/local.d/ /etc/dconf/db/local.d/
# Copy public key
COPY ./cosign.pub /usr/etc/pki/containers/cosign.pub
# Copy base signing config
COPY ./usr/etc/containers /usr/etc/
COPY rootfs/ /

RUN rpm-ostree install distrobox && \
    rpm-ostree override remove toolbox && \
    rpm-ostree install \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
    rpm-ostree install rpmfusion-free-release rpmfusion-nonfree-release \
    --uninstall rpmfusion-free-release \
    --uninstall rpmfusion-nonfree-release && \
####    rpm-ostree install intel-media-driver libva-intel-driver && \
    rpm-ostree install nextcloud-client nextcloud-client-nautilus && \
    rpm-ostree install neofetch && \
    rpm-ostree override remove mesa-va-drivers --install=mesa-va-drivers-freeworld --install=mesa-vdpau-drivers-freeworld && \
    rpm-ostree override remove firefox firefox-langpacks gnome-tour yelp gnome-color-manager && \
    rpm-ostree install ffmpeg gstreamer1-plugin-libav gstreamer1-plugins-bad-free-extras gstreamer1-plugins-bad-freeworld gstreamer1-plugins-ugly gstreamer1-vaapi steam-devices && \
    mkdir -p /etc/distrobox && \
    echo "container_image_default=\"registry.fedoraproject.org/fedora-toolbox:$(rpm -E %fedora)\"" >> /etc/distrobox/distrobox.conf && \
    # Setup container signing
    echo "Setup container signing in policy.json and cosign.yaml"
    echo "Registry to write: $IMAGE_REGISTRY"
    sed -i "s ghcr.io/ny5re $IMAGE_REGISTRY g" /usr/etc/containers/policy.json
    sed -i "s ghcr.io/ny5re $IMAGE_REGISTRY g" /usr/etc/containers/registries.d/cosign.yaml
    rpm-ostree cleanup -m && \
    ostree container commit
